const appleSources = {
 pro:'https://www.apple.com/newsroom/2026/09/apple-debuts-iphone-18-pro-and-iphone-18-pro-max/',
 duo:'https://www.apple.com/newsroom/2026/09/apple-unveils-iphone-duo/',
 lineup:'https://www.apple.com/newsroom/2026/09/get-ready-to-experience-iphone-18-pro-the-new-apple-watch-lineup-and-airpods-5/'
};
const applePost={id:'apple-2026',title:'iPhone 18 Pro, Pro Max y Duo: todo lo que dejó el evento de Apple',category:'Tecnología',date:'17 sep 2026',readTime:'4 minutos',image:'assets/apple-sketch.svg',excerpt:'Un iPhone que se abre, una nueva generación Pro y novedades para la muñeca, los oídos y el escritorio. Aquí van los apuntes.',content:`
<p>Septiembre siempre termina llenando el cuaderno de novedades. Esta vez, la presentación de Apple del 9 de septiembre de 2026 dejó una pregunta especialmente interesante: ¿queremos que el teléfono de siempre haga más cosas, o queremos que cambie de forma?</p>
<p>Los iPhone 18 Pro y Pro Max responden por el primer camino. El iPhone Duo explora el segundo. Y, entre ambos, hay relojes, auriculares y computadoras que también merecen una página.</p>
<h2>01 / iPhone 18 Pro y Pro Max</h2>
<p>Ambos estrenan el chip A20 Pro, una Dynamic Island más pequeña y una cámara principal Fusion de 48 MP con apertura variable. Esta última permite controlar cómo entra la luz y la profundidad de campo: una novedad especialmente interesante para quien disfruta haciendo fotos.</p>
<p>La nueva cámara de vapor se centra en mantener el rendimiento durante tareas exigentes. El Pro Max pone, además, especial énfasis en la autonomía. Los acabados son negro, plata, glacier y burgundy. La disponibilidad comienza el <strong>18 de septiembre</strong>.</p>
<p>Mi lectura: aquí la historia está en pulir la experiencia cotidiana. Si lo que te interesa es fotografía, rendimiento y batería, esta es la parte del anuncio que conviene mirar con calma, más allá del color nuevo.</p>
<p><a href="${appleSources.pro}" target="_blank" rel="noopener">Fuente: anuncio oficial de los iPhone 18 Pro ↗</a></p>
<h2>02 / iPhone Duo: el teléfono que abre otra página</h2>
<p>El Duo es el primer iPhone plegable de Apple. Combina una pantalla exterior de 5.4 pulgadas con una interior de 7.6 pulgadas; ambas ofrecen ProMotion. Lleva A20 Pro y Touch ID en el botón lateral. Sus colores son star white y night sky.</p>
<p>La preventa empieza el <strong>16 de octubre</strong> y llega el <strong>23 de octubre</strong>, con México entre los países anunciados para esa primera fecha. Apple también anuncia compatibilidad con Apple Pencil USB-C más adelante este año; no hay que confundir esa función futura con una prestación disponible desde el primer día.</p>
<p>Lo que más curiosidad me da es el cambio de uso: pasar de consultar algo rápidamente a abrir una superficie más amplia. El formato invita a pensar en lectura, mapas y varias tareas. Habrá que probarlo para saber cuánto aporta realmente en el día a día.</p>
<p><a href="${appleSources.duo}" target="_blank" rel="noopener">Fuente: presentación oficial del iPhone Duo ↗</a></p>
<h2>03 / También hubo novedades fuera del bolsillo</h2>
<ul><li><strong>Apple Watch Series 12 y Ultra 4:</strong> estrenan S11 y un nuevo sistema de sensores de salud.</li><li><strong>AirPods 5:</strong> mejoran la cancelación de ruido y añaden control de volumen deslizando sobre el auricular.</li><li><strong>Mac mini:</strong> incorpora opciones M6 y M5 Pro.</li><li><strong>Mac Studio:</strong> llega con M5 Max o M5 Ultra.</li></ul>
<p>Son propuestas para necesidades muy distintas. Un reloj vive contigo todo el día; una computadora depende mucho del trabajo que le pidas. Mi consejo editorial es empezar por lo que necesitas hacer, y después mirar el dispositivo.</p>
<h2>04 / Tres fechas para apuntar</h2>
<table><thead><tr><th>Productos</th><th>Lanzamiento · 2026</th></tr></thead><tbody><tr><td>iPhone 18 Pro / Pro Max, Watch Series 12 / Ultra 4 y AirPods 5</td><td>18 de septiembre</td></tr><tr><td>Mac mini y Mac Studio</td><td>22 de septiembre</td></tr><tr><td>iPhone Duo</td><td>23 de octubre</td></tr></tbody></table>
<p>Agrupé los contadores de la portada por fecha para que puedas seguir los lanzamientos sin repetir cinco veces el mismo reloj. El contador llega a cero al comenzar el día en Ciudad de México; la hora de venta y el inventario dependen de cada tienda.</p>
<p><a href="${appleSources.lineup}" target="_blank" rel="noopener">Fuente: calendario y resto de la gama en Apple Newsroom ↗</a></p>
<h2>Una última nota al margen</h2><p>El Duo se lleva el titular por el formato, pero no todos necesitamos lo mismo. Este especial reúne lo anunciado; no es una reseña de productos probados. Me quedo con la curiosidad de ver qué ideas nacen cuando una pantalla deja de tener una sola forma.</p><p class="hand">Nos leemos en la siguiente página. — Fluffy</p>`};
const posts=[applePost,...ARCHIVE.posts.slice().sort((a,b)=>new Date(b.date)-new Date(a.date))];
const launches=[{date:'2026-09-18',label:'18 SEP 2026',title:'El equipo de septiembre',products:'iPhone 18 Pro y Pro Max · Watch Series 12 y Ultra 4 · AirPods 5',icon:'✳'}, {date:'2026-09-22',label:'22 SEP 2026',title:'Un nuevo escritorio',products:'Mac mini · Mac Studio',icon:'⌘'},{date:'2026-10-23',label:'23 OCT 2026',title:'Se abre la era Duo',products:'iPhone Duo · Preventa: 16 de octubre',icon:'↗'}];
const $=s=>document.querySelector(s);const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#countdowns').innerHTML=launches.map(l=>`<article class="countdown-card"><div class="launch-top"><span>${l.label}</span><span aria-hidden="true">${l.icon}</span></div><h3>${l.title}</h3><p>${l.products}</p><div class="clock" data-date="${l.date}" role="timer" aria-label="Tiempo hasta ${l.label}"></div></article>`).join('');
function remaining(date,now=Date.now()){let s=Math.max(0,Math.floor((new Date(date+'T00:00:00-06:00').getTime()-now)/1000));return {done:s===0,values:[Math.floor(s/86400),Math.floor(s%86400/3600),Math.floor(s%3600/60),s%60]};}
function tick(){document.querySelectorAll('.clock').forEach(el=>{const r=remaining(el.dataset.date);el.innerHTML=r.done?'<span class="available">¡Llegó la fecha! ↗</span>':r.values.map((v,i)=>`<span>${String(v).padStart(2,'0')}<small>${['DÍAS','HORAS','MIN','SEG'][i]}</small></span>`).join('');});}tick();setInterval(tick,1000);
let category='Todo';let search='';const categories=['Todo',...new Set(posts.map(p=>p.category))];
$('#filters').innerHTML=categories.map(c=>`<button aria-pressed="${c===category}" data-category="${escapeHTML(c)}">${escapeHTML(c)}</button>`).join('');
function renderPosts(){const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const visible=posts.filter(p=>(category==='Todo'||p.category===category)&&normalize(p.title+' '+p.excerpt+' '+p.category).includes(normalize(search)));$('#posts').innerHTML=visible.map(p=>`<a class="post-card" href="#post-${p.id}"><div class="post-image"><img loading="lazy" src="${escapeHTML(p.image)}" alt="${escapeHTML(p.title)}"><span class="post-category">${escapeHTML(p.category)}</span></div><h3>${escapeHTML(p.title)}</h3><p>${escapeHTML(p.excerpt)}</p><div class="post-meta"><span>${escapeHTML(p.date)} · ${escapeHTML(p.readTime)}</span><span aria-hidden="true">↗</span></div></a>`).join('');$('#empty').hidden=visible.length>0;$('#posts').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.src='assets/Fluffy Saludando.png';},{once:true}));}
$('#filters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;category=b.dataset.category;$('#filters').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.category===category));renderPosts();});$('#search').addEventListener('input',e=>{search=e.target.value;renderPosts();});renderPosts();
const reader=$('#reader');let lastFocus;function showReader(html){lastFocus=document.activeElement;$('#reader-content').innerHTML=html;if(!reader.open)reader.showModal();reader.scrollTop=0;}
function linkedVideos(content){return content.replace(/\[video\s+(\d+)\]/gi,(_,id)=>{const v=ARCHIVE.videos.find(v=>v.id===Number(id));return v?`<p><a href="${escapeHTML(v.url)}" target="_blank" rel="noopener">▶ Ver ${escapeHTML(v.title)} ↗</a></p>`:'';});}
function route(){const match=location.hash.match(/^#post-(.+)$/)||location.hash.match(/^#\/post\/(\d+)$/);if(!match){if(reader.open)reader.close();return;}const p=posts.find(p=>String(p.id)===match[1]);if(!p)return;showReader(`<span class="eyebrow">${escapeHTML(p.category)} · ${escapeHTML(p.date)} · ${escapeHTML(p.readTime)}</span><h1>${escapeHTML(p.title)}</h1><img class="reader-image" src="${escapeHTML(p.image)}" alt="${escapeHTML(p.title)}">${linkedVideos(p.content)}`);$('#reader-content .reader-image').addEventListener('error',e=>{e.target.src='assets/Fluffy Saludando.png';},{once:true});}window.addEventListener('hashchange',route);route();
$('.reader-close').addEventListener('click',()=>reader.close());reader.addEventListener('click',e=>{if(e.target===reader){const r=reader.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)reader.close();}});reader.addEventListener('close',()=>{if(/^#(?:post-|\/post\/)/.test(location.hash))history.replaceState(null,'',location.pathname+location.search+'#entradas');if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});});
$('#videos').addEventListener('click',()=>showReader(`<span class="eyebrow">PARA VER CON CALMA</span><h1>El videocuaderno.</h1><div class="video-list">${ARCHIVE.videos.map(v=>`<a href="${escapeHTML(v.url)}" target="_blank" rel="noopener">▶ ${escapeHTML(v.title)} ↗</a>`).join('')}</div>`));
try{document.body.classList.toggle('dark',localStorage.getItem('fluffy-theme')==='dark');}catch{}$('#theme').addEventListener('click',()=>{const dark=document.body.classList.toggle('dark');try{localStorage.setItem('fluffy-theme',dark?'dark':'light');}catch{}});
